# Generated by Django 3.2.10 on 2022-05-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220503_1411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
